name: Post-run
description: "Tasks to run after pipeline is done"

inputs:
  dockerhub_token:
    description: "Docker Hub Token"
    required: true
  release_tag:
    description: "Release Tag"
    required: true

runs:
  using: "composite"
  steps:
    - name: Update Docker Hub Description
      uses: peter-evans/dockerhub-description@v5
      with:
        username: ${{ env.dockerhub_username }}
        password: ${{ inputs.dockerhub_token }}

    - name: Set job summary
      shell: bash
      run: |
        cat >> $GITHUB_STEP_SUMMARY <<EOB
        # Release Report
        ## Registries
        - [![Docker](https://img.shields.io/badge/docker-%230db7ed.svg?style=for-the-badge&logo=docker&logoColor=white)][docker_hub_url]
        - [![GitHub](https://img.shields.io/badge/ghcr.io-%23121011.svg?style=for-the-badge&logo=github&logoColor=white)][ghcr_io_url]
        
        ## Image Name
        > ${{ env.dockerhub_username }}/${{ env.image_name }}
        
        ## Latest Release
        [![GitHub](https://img.shields.io/badge/GitHub_Releases-%23121011.svg?style=for-the-badge&logo=github&logoColor=white)][gh_release_url]
        
        [docker_hub_url]: https://hub.docker.com/r/${{ env.dockerhub_username }}/${{ env.image_name }}
        [ghcr_io_url]: ${{ github.server_url}}/${{ github.repository }}/pkgs/container/${{ env.image_name }}
        [gh_release_url]: ${{ github.server_url}}/${{ github.repository }}/releases/latest
        EOB
