---
- name: Start Docker Compose
  hosts: 127.0.0.1
  connection: local
  gather_facts: false

  vars:
    ghostfolio_dir: "{{ lookup('env', 'GHOSTFOLIO_DIR') }}"
    postgres_port: "{{ lookup('env', 'POSTGRES_PORT') }}"
    redis_password: "{{ lookup('env', 'REDIS_PW') }}"
    postgres_db: "{{ lookup('env', 'POSTGRES_DB') }}"
    postgres_user: "{{ lookup('env', 'POSTGRES_USER') }}"
    postgres_password: "{{ lookup('env', 'POSTGRES_PW') }}"
    access_token_salt: "{{ lookup('env', 'ACCESS_TOKEN_SALT') }}"
    jtw_secret_key: "{{ lookup('env', 'JWT_SECRET') }}"

  tasks:
    - name: Create directory ghostfolio_dir
      file:
        path: "{{ ghostfolio_dir }}"
        state: directory
        owner: 99
        group: 100
        mode: 0775
        recurse: yes

    - name: Generate docker files
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      loop:
        - { src: templates/.env.j2, dest: "{{ ghostfolio_dir }}/.env" }
        - { src: templates/docker-compose.yml.j2, dest: "{{ ghostfolio_dir }}/docker-compose.yml" }

    - name: Stop existing docker compose containers
      command: docker-compose down --remove-orphans
      args:
        chdir: "{{ ghostfolio_dir }}"

    - name: Start Docker Compose
      command: docker-compose up --wait
      args:
        chdir: "{{ ghostfolio_dir }}"