name: Release Docker Image

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * 5'
  push:
    branches:
      - main

env:
  dockerhub_username: leonstoldt
  image_name: ghostfolio-installer

jobs:
  integration-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/integration-test

  release:
    needs: [integration-test]
    name: Build and push image
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "amd64"
            ansible_image_tag: "2.16-alpine-3.19"
          - platform: "arm64"
            ansible_image_tag: "alpine"
    permissions:
      contents: write
      packages: write
      # This is used to complete the identity challenge with sigstore/fulcio when running outside of PRs.
      id-token: write
    # https://github.com/orgs/community/discussions/17245
    outputs:
      digests: ${{ steps.build.outputs.digests }}
      tags_amd64: ${{ steps.build.outputs.tags_amd64 }}
      tags_arm64: ${{ steps.build.outputs.tags_arm64 }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/build-and-push
        id: build
        with:
          platform: ${{ matrix.platform }}
          ansible_image_tag: ${{ matrix.ansible_image_tag }}
          dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

  post-run:
    needs: [ release ]
    name: Post-run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/post-run
        with:
          dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
          digests: ${{ needs.release.outputs.digests }}
          tags_amd64: ${{ needs.release.outputs.tags_amd64 }}
          tags_arm64: ${{ needs.release.outputs.tags_arm64 }}
